// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetSociety.API.Models;

#nullable disable

namespace PetSociety.API.Migrations
{
    [DbContext(typeof(PetSocietyContext))]
    [Migration("20251216052608_AddResetToken")]
    partial class AddResetToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetSociety.API.Models.AcadamyBadge", b =>
                {
                    b.Property<int>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BadgeId"));

                    b.Property<string>("BadgeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BadgeId");

                    b.ToTable("AcadamyBadge", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityId"));

                    b.Property<byte>("ActivityCheck")
                        .HasColumnType("tinyint");

                    b.Property<string>("ActivityImg")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Activitie__Creat__2A164134");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationEndTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("RegistrationStartTime")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ActivityId")
                        .HasName("PK__Activiti__45F4A7F1CE963BFF");

                    b.HasIndex("MemberId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PetSociety.API.Models.ActivityAuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int")
                        .HasColumnName("new_status");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int")
                        .HasColumnName("previous_status");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("review_comment");

                    b.HasKey("LogId")
                        .HasName("PK__Activity__9E2397E0A647D286");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivityAuditLog", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.ActivityTag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<int>("TagCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("TagType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TagId")
                        .HasName("PK__Marks__4E30D34617074FDA");

                    b.HasIndex("TagCategoryId");

                    b.ToTable("ActivityTags");
                });

            modelBuilder.Entity("PetSociety.API.Models.ActivityTagsMapping", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TagId");

                    b.ToTable("ActivityTagsMappings");
                });

            modelBuilder.Entity("PetSociety.API.Models.AreaDetail", b =>
                {
                    b.Property<byte>("AreaId")
                        .HasColumnType("tinyint");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("AreaId");

                    b.ToTable("AreaDetails");
                });

            modelBuilder.Entity("PetSociety.API.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DisLike")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Like")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("Popular")
                        .HasColumnType("int");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ArticleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TagId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("PetSociety.API.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    b.Property<int>("TagId")
                        .HasColumnType("int")
                        .HasColumnName("TagID");

                    b.ToTable("ArticleTags");
                });

            modelBuilder.Entity("PetSociety.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PetSociety.API.Models.CertificateTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TemplateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TextLayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId");

                    b.ToTable("CertificateTemplate", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterQuiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuizId");

                    b.HasIndex("ChapterId");

                    b.ToTable("ChapterQuiz", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterQuizRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<byte?>("Score")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_ChapterQuizRecord_SubmittedAt");

                    b.HasKey("RecordId");

                    b.HasIndex("MemberId");

                    b.HasIndex("QuizId");

                    b.ToTable("ChapterQuizRecord", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterVideo", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("VideoId");

                    b.HasIndex("ChapterId");

                    b.ToTable("ChapterVideo", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.Collectible", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CollectibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectibleId"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasIndex("ArticleId");

                    b.HasIndex("MemberId");

                    b.ToTable("Collectibles");
                });

            modelBuilder.Entity("PetSociety.API.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime");

                    b.HasKey("CommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("MemberId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PetSociety.API.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinPurchase")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("PetSociety.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Courses_CreatedDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Type")
                        .HasColumnType("bit");

                    b.HasKey("CourseId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseCategory", b =>
                {
                    b.Property<byte>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<byte>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("CourseCategories");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseChapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChapterId");

                    b.HasIndex("CourseDetailId");

                    b.ToTable("CourseChapters");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseDetail", b =>
                {
                    b.Property<int>("CourseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseDetailId"));

                    b.Property<byte?>("AreaId")
                        .HasColumnType("tinyint");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CourseDetail_CreatedDate");

                    b.Property<DateTime?>("EndDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("InstructorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("StartDate")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("CourseDetailId")
                        .HasName("PK_CourseDetail");

                    b.HasIndex("AreaId");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseDetails");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseInstructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("InstructorId");

                    b.ToTable("CourseInstructor", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BuyerUserId")
                        .HasColumnType("int");

                    b.Property<int>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGift")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderedDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CourseOrders_OrderedDate");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiverEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyerUserId");

                    b.HasIndex("CourseDetailId");

                    b.ToTable("CourseOrders");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_CourseReviews_CreatedTime");

                    b.Property<byte>("Rating")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("CourseDetailId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseReviews");
                });

            modelBuilder.Entity("PetSociety.API.Models.EmailLog", b =>
                {
                    b.Property<int>("EmailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailId"));

                    b.Property<DateTime?>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_EmailLog_CreatedTime");

                    b.Property<int>("EmailType")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<byte?>("RetryCount")
                        .HasColumnType("tinyint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("EmailId");

                    b.HasIndex("EmailType");

                    b.ToTable("EmailLog", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.EmailType", b =>
                {
                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId");

                    b.ToTable("EmailTypes");
                });

            modelBuilder.Entity("PetSociety.API.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Favorites_Createdat");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<int>("TargetType")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId")
                        .HasName("PK_Favorites_1");

                    b.HasIndex("MemberId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("PetSociety.API.Models.ForumTag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("TagId")
                        .HasName("PK_Tags");

                    b.ToTable("ForumTags");
                });

            modelBuilder.Entity("PetSociety.API.Models.Landmark", b =>
                {
                    b.Property<int>("LandmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandmarkId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Landmarks__Creat__2BFE89A6");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(10, 8)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(11, 8)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LandmarkId")
                        .HasName("PK__Landmark__3195B57FDCCBC1D9");

                    b.HasIndex("MemberId");

                    b.ToTable("Landmarks");
                });

            modelBuilder.Entity("PetSociety.API.Models.LandmarkComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CommentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__LandmarkC__Creat__2B0A656D");

                    b.Property<string>("LandmarkComment1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LandmarkComment");

                    b.Property<int>("LandmarkId")
                        .HasColumnType("int")
                        .HasColumnName("LandmarkID");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__Landmark__C3B4DFAA704EAD1F");

                    b.HasIndex("LandmarkId");

                    b.HasIndex("MemberId");

                    b.ToTable("LandmarkComments");
                });

            modelBuilder.Entity("PetSociety.API.Models.LandmarkTag", b =>
                {
                    b.Property<int>("LandmarkId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasIndex("LandmarkId");

                    b.HasIndex("TagId");

                    b.ToTable("LandmarkTags");
                });

            modelBuilder.Entity("PetSociety.API.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Members_Isactive");

                    b.Property<DateTime?>("LastloginDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoginCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Members_Logincount");

                    b.Property<int>("LoginFailCount")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Members_LoginFailCount");

                    b.Property<int?>("LoginMethod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("ProfilePic")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Members_Registraterdate");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Members_Role");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("MemberId")
                        .HasName("PK_Members_1");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("PetSociety.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Notifications_Createdat");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("MemberId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PetSociety.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Orders_OrderDate");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserCouponId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("MemberId");

                    b.HasIndex("UserCouponId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PetSociety.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("PetSociety.API.Models.OrderLog", b =>
                {
                    b.Property<int>("OrderLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLogId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderLogs_LogDate");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderLogId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLogs");
                });

            modelBuilder.Entity("PetSociety.API.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF__Participa__Regis__4CA06362");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId")
                        .HasName("PK__Particip__7227997E3252CD6F");

                    b.HasIndex("ActivityId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("PetSociety.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<byte>("PaymentMethod")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A588ABCE3B9");

                    b.HasIndex("ParticipantId");

                    b.HasIndex(new[] { "TransactionId" }, "UQ__Payments__55433A4A24F64FFA")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("PetSociety.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_Products_CreateDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MemberId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductFavorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductFavorites_CreateDate");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFavorites");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_ProductReviews_ReviewDate");

                    b.HasKey("ReviewId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("PetSociety.API.Models.QuizOption", b =>
                {
                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int?>("IsCorrect")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("OptionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuizOption", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.QuizQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("QuestionText")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("QuizId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestion", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.ShoppingCart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_ShoppingCart_CreateDate");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("MemberId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCart", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.TagCategory", b =>
                {
                    b.Property<int>("TagCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagCategoryId"));

                    b.Property<string>("TagCategory1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("TagCategory");

                    b.HasKey("TagCategoryId")
                        .HasName("PK__MarkCate__122397E701691D6B");

                    b.HasIndex(new[] { "TagCategory1" }, "UQ__MarkCate__3A5A95C7C690C70A")
                        .IsUnique();

                    b.ToTable("TagCategories");
                });

            modelBuilder.Entity("PetSociety.API.Models.Ticket", b =>
                {
                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.HasIndex("ActivityId");

                    b.HasIndex("TicketTypeId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("PetSociety.API.Models.TicketType", b =>
                {
                    b.Property<int>("TicketTypeId")
                        .HasColumnType("int");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TicketTypeId");

                    b.ToTable("TicketType", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.UserAddress", b =>
                {
                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AddressId");

                    b.HasIndex("MemberId");

                    b.ToTable("UserAddress", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.UserBadge", b =>
                {
                    b.Property<int>("UserBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserBadgeId"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GrantedTime")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserBadge_GrantedTime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserBadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadge", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCertificate", b =>
                {
                    b.Property<int>("CertificateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertificateId"));

                    b.Property<int>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssueDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserCertificate_IssueDate");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("CertificateId");

                    b.HasIndex("CourseDetailId");

                    b.HasIndex("MemberId");

                    b.HasIndex("TemplateId");

                    b.ToTable("UserCertificate", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCoupon", b =>
                {
                    b.Property<int>("UserCouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserCouponId"));

                    b.Property<int>("CouponId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsedDate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserCoupons_UsedDate");

                    b.HasKey("UserCouponId");

                    b.HasIndex("CouponId");

                    b.HasIndex("MemberId");

                    b.ToTable("UserCoupons");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCourseRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<int>("LastChapterId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("(sysdatetime())")
                        .HasAnnotation("Relational:DefaultConstraintName", "DF_UserCourseRecord_UpdatedTime");

                    b.HasKey("RecordId")
                        .HasName("PK_UserCourseProgress");

                    b.HasIndex("CourseDetailId");

                    b.HasIndex("LastChapterId");

                    b.HasIndex("MemberId");

                    b.ToTable("UserCourseRecord", (string)null);
                });

            modelBuilder.Entity("PetSociety.API.Models.Video", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("CourseDetailId")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideoId"));

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("VideoURL");

                    b.HasIndex("ArticleId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("PetSociety.API.Models.Activity", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Activities")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Activities_Members");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.ActivityAuditLog", b =>
                {
                    b.HasOne("PetSociety.API.Models.Activity", "Activity")
                        .WithMany("ActivityAuditLogs")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityAuditLog_Activities");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("PetSociety.API.Models.ActivityTag", b =>
                {
                    b.HasOne("PetSociety.API.Models.TagCategory", "TagCategory")
                        .WithMany("ActivityTags")
                        .HasForeignKey("TagCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityTags_TagCategories");

                    b.Navigation("TagCategory");
                });

            modelBuilder.Entity("PetSociety.API.Models.ActivityTagsMapping", b =>
                {
                    b.HasOne("PetSociety.API.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityTagsMappings_Activities");

                    b.HasOne("PetSociety.API.Models.ActivityTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityTagsMappings_ActivityTags");

                    b.Navigation("Activity");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PetSociety.API.Models.Article", b =>
                {
                    b.HasOne("PetSociety.API.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Articles_Categories");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Articles")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Articles_Members");

                    b.HasOne("PetSociety.API.Models.ForumTag", "Tag")
                        .WithMany("Articles")
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_Articles_ForumTags");

                    b.Navigation("Category");

                    b.Navigation("Member");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterQuiz", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseChapter", "Chapter")
                        .WithMany("ChapterQuizzes")
                        .HasForeignKey("ChapterId")
                        .HasConstraintName("FK_ChapterQuiz_CourseChapters");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterQuizRecord", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("ChapterQuizRecords")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_ChapterQuizRecord_Members");

                    b.HasOne("PetSociety.API.Models.ChapterQuiz", "Quiz")
                        .WithMany("ChapterQuizRecords")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK_ChapterQuizRecord_ChapterQuiz");

                    b.Navigation("Member");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterVideo", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseChapter", "Chapter")
                        .WithMany("ChapterVideos")
                        .HasForeignKey("ChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_ChapterVideo_CourseChapters");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("PetSociety.API.Models.Collectible", b =>
                {
                    b.HasOne("PetSociety.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .IsRequired()
                        .HasConstraintName("FK_Collectibles_Articles");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Collectibles_Members");

                    b.Navigation("Article");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.Comment", b =>
                {
                    b.HasOne("PetSociety.API.Models.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Articles");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Comments")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Members");

                    b.Navigation("Article");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.Course", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseCategory", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Courses_CourseCategories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseChapter", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseDetail", "CourseDetail")
                        .WithMany("CourseChapters")
                        .HasForeignKey("CourseDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseChapters_CourseDetails");

                    b.Navigation("CourseDetail");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseDetail", b =>
                {
                    b.HasOne("PetSociety.API.Models.AreaDetail", "Area")
                        .WithMany("CourseDetails")
                        .HasForeignKey("AreaId")
                        .HasConstraintName("FK_CourseDetails_AreaDetails");

                    b.HasOne("PetSociety.API.Models.Course", "Course")
                        .WithMany("CourseDetails")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseDetails_Courses");

                    b.HasOne("PetSociety.API.Models.CourseInstructor", "Instructor")
                        .WithMany("CourseDetails")
                        .HasForeignKey("InstructorId")
                        .HasConstraintName("FK_CourseDetails_CourseInstructor");

                    b.Navigation("Area");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseOrder", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "BuyerUser")
                        .WithMany("CourseOrders")
                        .HasForeignKey("BuyerUserId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseOrders_Members");

                    b.HasOne("PetSociety.API.Models.CourseDetail", "CourseDetail")
                        .WithMany("CourseOrders")
                        .HasForeignKey("CourseDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseOrders_CourseDetails");

                    b.Navigation("BuyerUser");

                    b.Navigation("CourseDetail");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseReview", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseDetail", "CourseDetail")
                        .WithMany("CourseReviews")
                        .HasForeignKey("CourseDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseReviews_CourseDetails");

                    b.HasOne("PetSociety.API.Models.Member", "User")
                        .WithMany("CourseReviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_CourseReviews_Members");

                    b.Navigation("CourseDetail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetSociety.API.Models.EmailLog", b =>
                {
                    b.HasOne("PetSociety.API.Models.EmailType", "EmailTypeNavigation")
                        .WithMany("EmailLogs")
                        .HasForeignKey("EmailType")
                        .IsRequired()
                        .HasConstraintName("FK_EmailLog_EmailTypes");

                    b.Navigation("EmailTypeNavigation");
                });

            modelBuilder.Entity("PetSociety.API.Models.Favorite", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Favorites")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Favorites_Members");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.Landmark", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Landmarks")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Landmarks_Members");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.LandmarkComment", b =>
                {
                    b.HasOne("PetSociety.API.Models.Landmark", "Landmark")
                        .WithMany("LandmarkComments")
                        .HasForeignKey("LandmarkId")
                        .IsRequired()
                        .HasConstraintName("FK_LandmarkComments_Landmarks");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("LandmarkComments")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_LandmarkComments_Members");

                    b.Navigation("Landmark");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.LandmarkTag", b =>
                {
                    b.HasOne("PetSociety.API.Models.Landmark", "Landmark")
                        .WithMany()
                        .HasForeignKey("LandmarkId")
                        .IsRequired()
                        .HasConstraintName("FK_LandmarkTags_Landmarks");

                    b.HasOne("PetSociety.API.Models.ActivityTag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .IsRequired()
                        .HasConstraintName("FK_LandmarkTags_ActivityTags");

                    b.Navigation("Landmark");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PetSociety.API.Models.Notification", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Notifications")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Members");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.Order", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Orders")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Members");

                    b.HasOne("PetSociety.API.Models.UserCoupon", "UserCoupon")
                        .WithMany("Orders")
                        .HasForeignKey("UserCouponId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_UserCoupons");

                    b.Navigation("Member");

                    b.Navigation("UserCoupon");
                });

            modelBuilder.Entity("PetSociety.API.Models.OrderDetail", b =>
                {
                    b.HasOne("PetSociety.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.HasOne("PetSociety.API.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetSociety.API.Models.OrderLog", b =>
                {
                    b.HasOne("PetSociety.API.Models.Order", "Order")
                        .WithMany("OrderLogs")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderLogs_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PetSociety.API.Models.Participant", b =>
                {
                    b.HasOne("PetSociety.API.Models.Activity", "Activity")
                        .WithMany("Participants")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Participants_Activities");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Participants")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Participants_Members");

                    b.HasOne("PetSociety.API.Models.TicketType", "TicketType")
                        .WithMany("Participants")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Participants_TicketType");

                    b.Navigation("Activity");

                    b.Navigation("Member");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("PetSociety.API.Models.Payment", b =>
                {
                    b.HasOne("PetSociety.API.Models.Participant", "Participant")
                        .WithMany("Payments")
                        .HasForeignKey("ParticipantId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Participants");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("PetSociety.API.Models.Product", b =>
                {
                    b.HasOne("PetSociety.API.Models.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_ProductCategories");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("Products")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_Products_Members");

                    b.Navigation("Category");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductFavorite", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("ProductFavorites")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductFavorites_Members");

                    b.HasOne("PetSociety.API.Models.Product", "Product")
                        .WithMany("ProductFavorites")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductFavorites_Products");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductImage", b =>
                {
                    b.HasOne("PetSociety.API.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductImages_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductReview", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("ProductReviews")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviews_Members");

                    b.HasOne("PetSociety.API.Models.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductReviews_Products");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetSociety.API.Models.QuizOption", b =>
                {
                    b.HasOne("PetSociety.API.Models.QuizQuestion", "Question")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK_QuizOption_QuizQuestion");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PetSociety.API.Models.QuizQuestion", b =>
                {
                    b.HasOne("PetSociety.API.Models.ChapterQuiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .HasConstraintName("FK_QuizQuestion_ChapterQuiz");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("PetSociety.API.Models.ShoppingCart", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingCart_Members");

                    b.HasOne("PetSociety.API.Models.Product", "Product")
                        .WithMany("ShoppingCarts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ShoppingCart_Products");

                    b.Navigation("Member");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PetSociety.API.Models.Ticket", b =>
                {
                    b.HasOne("PetSociety.API.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_Activities");

                    b.HasOne("PetSociety.API.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Tickets_TicketType");

                    b.Navigation("Activity");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserAddress", b =>
                {
                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("UserAddresses")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_UserAddress_Members");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserBadge", b =>
                {
                    b.HasOne("PetSociety.API.Models.AcadamyBadge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBadge_AcadamyBadge");

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCertificate", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseDetail", "CourseDetail")
                        .WithMany("UserCertificates")
                        .HasForeignKey("CourseDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCertificate_CourseDetails");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("UserCertificates")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCertificate_Members");

                    b.HasOne("PetSociety.API.Models.CertificateTemplate", "Template")
                        .WithMany("UserCertificates")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK_UserCertificate_CertificateTemplate");

                    b.Navigation("CourseDetail");

                    b.Navigation("Member");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCoupon", b =>
                {
                    b.HasOne("PetSociety.API.Models.Coupon", "Coupon")
                        .WithMany("UserCoupons")
                        .HasForeignKey("CouponId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCoupons_Coupons");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("UserCoupons")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCoupons_Members");

                    b.Navigation("Coupon");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCourseRecord", b =>
                {
                    b.HasOne("PetSociety.API.Models.CourseDetail", "CourseDetail")
                        .WithMany("UserCourseRecords")
                        .HasForeignKey("CourseDetailId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseRecord_CourseDetails");

                    b.HasOne("PetSociety.API.Models.CourseChapter", "LastChapter")
                        .WithMany("UserCourseRecords")
                        .HasForeignKey("LastChapterId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseRecord_CourseChapters");

                    b.HasOne("PetSociety.API.Models.Member", "Member")
                        .WithMany("UserCourseRecords")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("FK_UserCourseRecord_Members");

                    b.Navigation("CourseDetail");

                    b.Navigation("LastChapter");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PetSociety.API.Models.Video", b =>
                {
                    b.HasOne("PetSociety.API.Models.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .IsRequired()
                        .HasConstraintName("FK_Videos_Articles");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("PetSociety.API.Models.AcadamyBadge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("PetSociety.API.Models.Activity", b =>
                {
                    b.Navigation("ActivityAuditLogs");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PetSociety.API.Models.AreaDetail", b =>
                {
                    b.Navigation("CourseDetails");
                });

            modelBuilder.Entity("PetSociety.API.Models.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PetSociety.API.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("PetSociety.API.Models.CertificateTemplate", b =>
                {
                    b.Navigation("UserCertificates");
                });

            modelBuilder.Entity("PetSociety.API.Models.ChapterQuiz", b =>
                {
                    b.Navigation("ChapterQuizRecords");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("PetSociety.API.Models.Coupon", b =>
                {
                    b.Navigation("UserCoupons");
                });

            modelBuilder.Entity("PetSociety.API.Models.Course", b =>
                {
                    b.Navigation("CourseDetails");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseCategory", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseChapter", b =>
                {
                    b.Navigation("ChapterQuizzes");

                    b.Navigation("ChapterVideos");

                    b.Navigation("UserCourseRecords");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseDetail", b =>
                {
                    b.Navigation("CourseChapters");

                    b.Navigation("CourseOrders");

                    b.Navigation("CourseReviews");

                    b.Navigation("UserCertificates");

                    b.Navigation("UserCourseRecords");
                });

            modelBuilder.Entity("PetSociety.API.Models.CourseInstructor", b =>
                {
                    b.Navigation("CourseDetails");
                });

            modelBuilder.Entity("PetSociety.API.Models.EmailType", b =>
                {
                    b.Navigation("EmailLogs");
                });

            modelBuilder.Entity("PetSociety.API.Models.ForumTag", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("PetSociety.API.Models.Landmark", b =>
                {
                    b.Navigation("LandmarkComments");
                });

            modelBuilder.Entity("PetSociety.API.Models.Member", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Articles");

                    b.Navigation("ChapterQuizRecords");

                    b.Navigation("Comments");

                    b.Navigation("CourseOrders");

                    b.Navigation("CourseReviews");

                    b.Navigation("Favorites");

                    b.Navigation("LandmarkComments");

                    b.Navigation("Landmarks");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");

                    b.Navigation("Participants");

                    b.Navigation("ProductFavorites");

                    b.Navigation("ProductReviews");

                    b.Navigation("Products");

                    b.Navigation("ShoppingCarts");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserCertificates");

                    b.Navigation("UserCoupons");

                    b.Navigation("UserCourseRecords");
                });

            modelBuilder.Entity("PetSociety.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderLogs");
                });

            modelBuilder.Entity("PetSociety.API.Models.Participant", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("PetSociety.API.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("ProductFavorites");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductReviews");

                    b.Navigation("ShoppingCarts");
                });

            modelBuilder.Entity("PetSociety.API.Models.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PetSociety.API.Models.QuizQuestion", b =>
                {
                    b.Navigation("QuizOptions");
                });

            modelBuilder.Entity("PetSociety.API.Models.TagCategory", b =>
                {
                    b.Navigation("ActivityTags");
                });

            modelBuilder.Entity("PetSociety.API.Models.TicketType", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PetSociety.API.Models.UserCoupon", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
