// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ActivityGuide
{
    public int GuideId { get; set; }

    public int ActivityId { get; set; }

    public DateTime? PublishDate { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string ActivityEditorHtml { get; set; }

    public virtual Activity Activity { get; set; }
}