// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ActivityTag
{
    public int TagId { get; set; }

    public string TagType { get; set; }

    public int TagCategoryId { get; set; }

    public virtual TagCategory TagCategory { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();
}