// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class Article
{
    public int ArticleId { get; set; }

    public int CategoryId { get; set; }

    public int TagId { get; set; }

    public int MemberId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public DateTime PostDate { get; set; }

    public DateTime LastUpdate { get; set; }

    public int? Like { get; set; }

    public int? DisLike { get; set; }

    public int? Popular { get; set; }

    public int? CommentCount { get; set; }

    public string Picture { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual ICollection<FavoriteArticle> FavoriteArticles { get; set; } = new List<FavoriteArticle>();

    public virtual Member Member { get; set; }

    public virtual ForumTag Tag { get; set; }
}