// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ChapterQuiz
{
    public int QuizId { get; set; }

    public int? ChapterId { get; set; }

    public string Title { get; set; }

    public virtual CourseChapter Chapter { get; set; }

    public virtual ICollection<ChapterQuizRecord> ChapterQuizRecords { get; set; } = new List<ChapterQuizRecord>();

    public virtual ICollection<QuizQuestion> QuizQuestions { get; set; } = new List<QuizQuestion>();
}