// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ChapterVideo
{
    public int VideoId { get; set; }

    public int? CourseDetailId { get; set; }

    public int ChapterId { get; set; }

    public string VideoUrl { get; set; }

    public virtual CourseChapter Chapter { get; set; }
}