// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ChapterQuizRecord
{
    public int RecordId { get; set; }

    public int MemberId { get; set; }

    public int QuizId { get; set; }

    public byte? CorrectCount { get; set; }

    public byte? Score { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual Member Member { get; set; }

    public virtual ChapterQuiz Quiz { get; set; }
}