// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class CourseOrder
{
    public int OrderId { get; set; }

    public int CourseDetailId { get; set; }

    public string CourseTitle { get; set; }

    public int BuyerMemberId { get; set; }

    public string MerchantTradeNo { get; set; }

    public bool IsGift { get; set; }

    public string ReceiverEmail { get; set; }

    public string ReceiverName { get; set; }

    public decimal? Amount { get; set; }

    public int OrderStatus { get; set; }

    public string PaymentMethod { get; set; }

    public string TransactionId { get; set; }

    public bool IsPaid { get; set; }

    public DateTime? OrderedDate { get; set; }

    public DateTime? PaymentDate { get; set; }

    public virtual Member BuyerMember { get; set; }
}