// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class CourseReview
{
    public int ReviewId { get; set; }

    public int CourseDetailId { get; set; }

    public int UserId { get; set; }

    public string Comment { get; set; }

    public byte Rating { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual CourseDetail CourseDetail { get; set; }

    public virtual Member User { get; set; }
}