// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class EmailLog
{
    public int EmailId { get; set; }

    public int EmailType { get; set; }

    public string ReceiverEmail { get; set; }

    public bool Status { get; set; }

    public string ErrorMessage { get; set; }

    public byte? RetryCount { get; set; }

    public DateTime? CreatedTime { get; set; }

    public virtual EmailType EmailTypeNavigation { get; set; }
}