// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class LandmarkComment
{
    public int CommentId { get; set; }

    public int LandmarkId { get; set; }

    public string LandmarkComment1 { get; set; }

    public DateTime CreateDate { get; set; }

    public int MemberId { get; set; }

    public virtual Landmark Landmark { get; set; }

    public virtual Member Member { get; set; }
}