// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class Landmark
{
    public int LandmarkId { get; set; }

    public string Name { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string Category { get; set; }

    public DateTime CreatedDate { get; set; }

    public int MemberId { get; set; }

    public virtual ICollection<LandmarkComment> LandmarkComments { get; set; } = new List<LandmarkComment>();

    public virtual Member Member { get; set; }
}