// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public int? UserCouponId { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal FinalAmount { get; set; }

    public DateTime OrderDate { get; set; }

    public string ShippingAddress { get; set; }

    public string OrderStatus { get; set; }

    public string PaymentStatus { get; set; }

    public string PaymentMethod { get; set; }

    public string MerchantTradeNo { get; set; }

    public string TradeNo { get; set; }

    public DateTime? TradeDate { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverPhone { get; set; }

    public string ReceiverEmail { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderLog> OrderLogs { get; set; } = new List<OrderLog>();

    public virtual UserCoupon UserCoupon { get; set; }
}