// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class Participant
{
    public int ParticipantId { get; set; }

    public int ActivityId { get; set; }

    public int MemberId { get; set; }

    public DateTime RegistrationDate { get; set; }

    public string PaymentStatus { get; set; }

    public string Notes { get; set; }

    public virtual Activity Activity { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}