// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ProductReview
{
    public int ReviewId { get; set; }

    public int ProductId { get; set; }

    public int MemberId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime ReviewDate { get; set; }

    public virtual Member Member { get; set; }

    public virtual Product Product { get; set; }
}