// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class ShoppingCart
{
    public int CartId { get; set; }

    public int MemberId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual Member Member { get; set; }

    public virtual Product Product { get; set; }
}