// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class TagCategory
{
    public int TagCategoryId { get; set; }

    public string TagCategory1 { get; set; }

    public virtual ICollection<ActivityTag> ActivityTags { get; set; } = new List<ActivityTag>();
}