// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class UserAddress
{
    public int AddressId { get; set; }

    public int MemberId { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverPhone { get; set; }

    public string Address { get; set; }

    public bool IsDefault { get; set; }

    public virtual Member Member { get; set; }
}