// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class UserBadge
{
    public int UserBadgeId { get; set; }

    public int UserId { get; set; }

    public int BadgeId { get; set; }

    public DateTime? GrantedTime { get; set; }

    public virtual AcadamyBadge Badge { get; set; }
}