// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class UserCertificate
{
    public int CertificateId { get; set; }

    public int MemberId { get; set; }

    public int CourseDetailId { get; set; }

    public int? TemplateId { get; set; }

    public DateTime? IssueDate { get; set; }

    public virtual CourseDetail CourseDetail { get; set; }

    public virtual Member Member { get; set; }

    public virtual CertificateTemplate Template { get; set; }
}