// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetSociety.API.Models;

public partial class Video
{
    public int VideoId { get; set; }

    public int ArticleId { get; set; }

    public int? CourseDetailId { get; set; }

    public string VideoUrl { get; set; }

    public virtual Article Article { get; set; }
}